export const GENDER = [
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'non-binary', label: 'Non-binary' },
  { value: 'genderqueer', label: 'Genderqueer' },
  { value: 'genderfluid', label: 'Genderfluid' },
  { value: 'agender', label: 'Agender' },
  { value: 'pangender', label: 'Pangender' },
  { value: 'two-spirit', label: 'Two-spirit' },
  { value: 'transgender', label: 'Transgender' },
  { value: 'intersex', label: 'Intersex' },
  { value: 'androgyne', label: 'Androgyne' },
  { value: 'bigender', label: 'Bigender' },
  { value: 'neutrois', label: 'Neutrois' },
  { value: 'other', label: 'Other' },
] as const;

export const ROLE = [
  { value: 'user', label: 'User' },
  { value: 'admin', label: 'Admin' },
] as const;

export const STATUS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
] as const;

export const PRONOUNS = [
  { value: 'he', label: 'He/Him' },
  { value: 'she', label: 'She/Her' },
  { value: 'they', label: 'They/Them' },
  { value: 'other', label: 'Other' },
] as const;

// connecticut counties only in alphabetical order
export const LOCATION = [
  { value: 'Fairfield', label: 'Fairfield' },
  { value: 'Hartford', label: 'Hartford' },
  { value: 'Litchfield', label: 'Litchfield' },
  { value: 'Middlesex', label: 'Middlesex' },
  { value: 'New Haven', label: 'New Haven' },
  { value: 'New London', label: 'New London' },
  { value: 'Tolland', label: 'Tolland' },
  { value: 'Windham', label: 'Windham' },
] as const;

// user interests and hobbies -- added to database
export const INTERESTS = {
  food: [
    { label: 'Pizza', value: 'pizza' },
    { label: 'Sushi', value: 'sushi' },
    { label: 'Burgers', value: 'burgers' },
    { label: 'Pasta', value: 'pasta' },
    { label: 'Salad', value: 'salad' },
    { label: 'Tacos', value: 'tacos' },
    { label: 'ice cream', value: 'ice cream' },
    { label: 'Other', value: 'other' },
  ],
  sports: [
    { label: 'Football', value: 'football' },
    { label: 'Basketball', value: 'basketball' },
    { label: 'Tennis', value: 'tennis' },
    { label: 'Soccer', value: 'soccer' },
    { label: 'Baseball', value: 'baseball' },
    { label: 'Cricket', value: 'cricket' },
    { label: 'Lacrosse', value: 'lacrosse' },
    { label: 'Frisbee', value: 'frisbee' },
    { label: 'Swimming', value: 'swimming' },
    { label: 'Running', value: 'running' },
    { label: 'Cycling', value: 'cycling' },
    { label: 'Golf', value: 'golf' },
    { label: 'Hockey', value: 'hockey' },
    { label: 'Rugby', value: 'rugby' },
    { label: 'Track & Field', value: 'track and field' },
    { label: 'Other', value: 'other' },
  ],
  hobbies: [
    { label: 'Reading', value: 'reading' },
    { label: 'Gardening', value: 'gardening' },
    { label: 'Photography', value: 'photography' },
    { label: 'Painting', value: 'painting' },
    { label: 'Cooking', value: 'cooking' },
    { label: 'Traveling', value: 'traveling' },
    { label: 'Knitting', value: 'knitting' },
    { label: 'Woodworking', value: 'woodworking' },
    { label: 'Writing', value: 'writing' },
    { label: 'Music', value: 'music' },
    { label: 'Gaming', value: 'gaming' },
    { label: 'Dancing', value: 'dancing' },
    { label: 'Fishing', value: 'fishing' },
    { label: 'Hiking', value: 'hiking' },
    { label: 'Other', value: 'other' },
  ],
  music: [
    { label: 'Rock', value: 'rock' },
    { label: 'Pop', value: 'pop' },
    { label: 'Jazz', value: 'jazz' },
    { label: 'Classical', value: 'classical' },
    { label: 'Hip-hop', value: 'hiphop' },
    { label: 'Rap', value: 'rap' },
    { label: 'Country', value: 'country' },
    { label: 'Electronic', value: 'electronic' },
    { label: 'Alternative', value: 'alternative' },
    { label: 'Folk', value: 'folk' },
    { label: 'Classical', value: 'classical' },
    { label: 'Blues', value: 'blues' },
    { label: 'Other', value: 'other' },
  ],
  movies: [
    { label: 'Action', value: 'action' },
    { label: 'Comedy', value: 'comedy' },
    { label: 'Drama', value: 'drama' },
    { label: 'Horror', value: 'horror' },
    { label: 'Romance', value: 'romance' },
    { label: 'Sci-Fi', value: 'scifi' },
    { label: 'Documentary', value: 'documentary' },
    { label: 'Animation', value: 'animation' },
    { label: 'Other', value: 'other' },
  ],
  travel: [
    { label: 'Beach', value: 'beach' },
    { label: 'Mountains', value: 'mountains' },
    { label: 'City Exploration', value: 'city_exploration' },
    { label: 'Backpacking', value: 'backpacking' },
    { label: 'Road Trips', value: 'road_trips' },
    { label: 'Cruises', value: 'cruises' },
    { label: 'Camping', value: 'camping' },
    { label: 'Adventure Travel', value: 'adventure_travel' },
    { label: 'Other', value: 'other' },
  ],
  books: [
    { label: 'Fiction', value: 'fiction' },
    { label: 'Non-Fiction', value: 'non_fiction' },
    { label: 'Fantasy', value: 'fantasy' },
    { label: 'Mystery', value: 'mystery' },
    { label: 'Self-Help', value: 'self_help' },
    { label: 'Biography', value: 'biography' },
    { label: 'Science Fiction', value: 'science_fiction' },
    { label: 'Historical', value: 'historical' },
    { label: 'Other', value: 'other' },
  ],
  technology: [
    { label: 'AI & Machine Learning', value: 'ai_ml' },
    { label: 'Blockchain', value: 'blockchain' },
    { label: 'Cloud Computing', value: 'cloud_computing' },
    { label: 'Cybersecurity', value: 'cybersecurity' },
    { label: 'Gaming', value: 'gaming' },
    { label: 'Robotics', value: 'robotics' },
    { label: 'AR/VR', value: 'ar_vr' },
    { label: 'Web Development', value: 'web_dev' },
    { label: 'Other', value: 'other' },
  ],
  fashion: [
    { label: 'Streetwear', value: 'streetwear' },
    { label: 'Vintage', value: 'vintage' },
    { label: 'Formal', value: 'formal' },
    { label: 'Casual', value: 'casual' },
    { label: 'Athleisure', value: 'athleisure' },
    { label: 'Sustainable Fashion', value: 'sustainable_fashion' },
    { label: 'Luxury Brands', value: 'luxury_brands' },
    { label: 'DIY Fashion', value: 'diy_fashion' },
    { label: 'Other', value: 'other' },
  ],
  fitness: [
    { label: 'Yoga', value: 'yoga' },
    { label: 'CrossFit', value: 'crossfit' },
    { label: 'Weightlifting', value: 'weightlifting' },
    { label: 'Pilates', value: 'pilates' },
    { label: 'Cycling', value: 'cycling' },
    { label: 'Running', value: 'running' },
    { label: 'Martial Arts', value: 'martial_arts' },
    { label: 'Dance Fitness', value: 'dance_fitness' },
    { label: 'Other', value: 'other' },
  ],
  gaming: [
    { label: 'Action RPGs', value: 'action_rpg' },
    { label: 'MMORPGs', value: 'mmorpg' },
    { label: 'First-Person Shooters', value: 'fps' },
    { label: 'Puzzle Games', value: 'puzzle_games' },
    { label: 'Strategy Games', value: 'strategy_games' },
    { label: 'Simulation Games', value: 'simulation_games' },
    { label: 'Mobile Games', value: 'mobile_games' },
    { label: 'Indie Games', value: 'indie_games' },
    { label: 'Other', value: 'other' },
  ],
  pets: [
    { label: 'Dogs', value: 'dogs' },
    { label: 'Cats', value: 'cats' },
    { label: 'Reptiles', value: 'reptiles' },
    { label: 'Birds', value: 'birds' },
    { label: 'Aquarium Fish', value: 'aquarium_fish' },
    { label: 'Exotic Pets', value: 'exotic_pets' },
    { label: 'Small Mammals', value: 'small_mammals' },
    { label: 'Pet Training', value: 'pet_training' },
    { label: 'Other', value: 'other' },
  ],
  wellness: [
    { label: 'Meditation', value: 'meditation' },
    { label: 'Mindfulness', value: 'mindfulness' },
    { label: 'Aromatherapy', value: 'aromatherapy' },
    { label: 'Spa Treatments', value: 'spa_treatments' },
    { label: 'Nutrition', value: 'nutrition' },
    { label: 'Mental Health', value: 'mental_health' },
    { label: 'Holistic Health', value: 'holistic_health' },
    { label: 'Sleep Wellness', value: 'sleep_wellness' },
    { label: 'Other', value: 'other' },
  ],
  art: [
    { label: 'Sculpting', value: 'sculpting' },
    { label: 'Digital Art', value: 'digital_art' },
    { label: 'Sketching', value: 'sketching' },
    { label: 'Street Art', value: 'street_art' },
    { label: 'Collage', value: 'collage' },
    { label: 'Ceramics', value: 'ceramics' },
    { label: 'Printmaking', value: 'printmaking' },
    { label: 'Tattoo Art', value: 'tattoo_art' },
    { label: 'Other', value: 'other' },
  ],
  cars: [
    { label: 'Classic Cars', value: 'classic_cars' },
    { label: 'Supercars', value: 'supercars' },
    { label: 'Off-Roading', value: 'off_roading' },
    { label: 'Motorcycles', value: 'motorcycles' },
    { label: 'Electric Cars', value: 'electric_cars' },
    { label: 'Car Restoration', value: 'car_restoration' },
    { label: 'Motorsports', value: 'motorsports' },
    { label: 'Other', value: 'other' },
  ],
} as const;

export const LOOKING_FOR = [
  { value: 'friends', type: 'Friends' },
  {
    value: 'short_term_relationship',
    type: 'A short-term Relationship',
  },
  {
    value: 'long_term_relationship',
    type: 'A long-term Relationship',
  },
  { value: 'Life_partnership', type: 'A Life Partner' },
  { value: 'fwb', type: 'Friends with benefits' },
  { value: 'hookups', type: 'Hookups' },
  { value: 'ons', type: 'One night stands' },
  { value: 'bdsm_kink', type: 'BDSM/Kink' },
  { value: 'party', type: 'To party' },
  { value: 'other', type: 'Something else' },
] as const;
